### ISSUE TITLE
building PDU with wrong escape sequence

### ISSUE THREAD

**Issue by gillesbourgeois** [artemiosv/etfa2015#1]
from mtf.py in  def getSupportedFunctionCodes(self):
for fct in range(0,127,1):
pdu=struct.pack(">B",fct) +'\0x00\0x00'+'\0x00\0x01'
the escape sequence is invalidated by the  '0 before the 'x'', resulting in two extra digits in pdu
also two other '\0x in mtf.py

**Comment by artemiosv** [comment]
Correct! Nice catch :)
